// -------- Bands --------
export const bands = [
    {
        name: "Morpheus",
        members: [
            {firstName: "Davidson", lastName: "Fong", roles: ["vocals", "guitar"], images: []},
            {firstName: "Brian", lastName: "Green", roles: ["bass"], images: []},
            {firstName: "Javan", lastName: "Campbell", roles: ["drums"], images: []},
            {firstName: "Jerimiah", lastName: "King", roles: ["keyboard"], images: []},
        ],
        events: [
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
        ],
        mediaLinks: [ {facebook: "facebook"}, {instagram: "instagram"}, {spotify: "spotify"}, {tiktok: "tiktok"}, {twitter: "twittter"}, {youtube: "youtube"} ],
        calendarType: "google",
        calendarID: "string",
        images: ["string"],
        genres: ["pop", "rock", "top40", "reggae"],
        biography: "This is a biography.",
        
    },
    {
        name: "Black Diamond Band",
        members: [
            {firstName: "Christian", lastName: "Smalls", roles: ["vocals", "guitar"], images: []},
            {firstName: "Randy", lastName: "Stevens", roles: ["bass"], images: []},
            {firstName: "AJ", lastName: "Jenkins", roles: ["drums"], images: []},
            {firstName: "Michael", lastName: "Stevens", roles: ["keyboard"], images: []},
        ],
        events: [
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
        ],
        mediaLinks: [ {facebook: "facebook"}, {instagram: "instagram"}, {spotify: "spotify"}, {tiktok: "tiktok"}, {twitter: "twittter"}, {youtube: "youtube"} ],
        calendarType: "google",
        calendarID: "string",
        images: ["string"],
        genres: ["pop", "rock", "top40", "reggae"],
        biography: "This is a biography.",

    },
    {
        name: "Bender Funk",
        members: [
            {firstName: "Jaymee", lastName: "Zdanek", roles: ["vocals"], images: []},
            {firstName: "David", lastName: "Sink", roles: ["guitar"], images: []},
            {firstName: "Mike", lastName: "Brown", roles: ["drums"], images: []},
            {firstName: "Woody", lastName: "Woodcock", roles: ["bass"], images: []},
        ],
        events: [
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
        ],
        mediaLinks: [ {facebook: "facebook"}, {instagram: "instagram"}, {spotify: "spotify"}, {tiktok: "tiktok"}, {twitter: "twittter"}, {youtube: "youtube"} ],
        calendarType: "google",
        calendarID: "string",
        images: ["string"],
        genres: ["pop", "rock", "top40", "reggae"],
        biography: "This is a biography.",
    },
    {
        name: "PsychoDelics",
        members: [
            {firstName: "Cameron", lastName: "Westcott", roles: ["vocals", "bass"], images: []},
            {firstName: "Whit", lastName: "Burns", roles: ["guitar"], images: []},
            {firstName: "Sean", lastName: "Bing", roles: ["drums, vocals"], images: []},
            {firstName: "Noah", lastName: "Jones", roles: ["keyboard"], images: []},
        ],
        events: [
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
            {startTime: "startTime", endTime: "endTime", location: {name: "String", address: "String"}},
        ],
        mediaLinks: [ {facebook: "facebook"}, {instagram: "instagram"}, {spotify: "spotify"}, {tiktok: "tiktok"}, {twitter: "twittter"}, {youtube: "youtube"} ],
        calendarType: "google",
        calendarID: "string",
        images: ["string"],
        genres: ["pop", "rock", "top40", "reggae"],
        biography: "This is a biography.",
    },
]



// -------- Venues --------
export const venues = [
    
]